---

- name: reload systemd
  ansible.builtin.command:
    systemctl daemon-reload
  become: yes

- name: system restart seafile
  ansible.builtin.service:
    name: seafile
    state: restarted
    use: '{{ seafile_daemon_mode }}'
  become: yes

- name: system restart seahub
  ansible.builtin.service:
    name: seahub
    state: restarted
    use: '{{ seafile_daemon_mode }}'
  become: yes

- name: system reload seafile
  ansible.builtin.service:
    name: seafile
    state: reloaded
    use: '{{ seafile_daemon_mode }}'
  become: yes

- name: system reload seahub
  ansible.builtin.service:
    name: seahub
    state: reloaded
    use: '{{ seafile_daemon_mode }}'
  become: yes
